import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';

const fontConfig = {
  displayLarge: {
    fontFamily: 'Inter_400Regular',
    fontSize: 57,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'Inter_400Regular',
    fontSize: 45,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'Inter_400Regular',
    fontSize: 36,
    fontWeight: '400' as const,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 32,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 28,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 24,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 22,
    fontWeight: '600' as const,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 16,
    fontWeight: '600' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    fontWeight: '600' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'Inter_500Medium',
    fontSize: 14,
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    fontWeight: '400' as const,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    fontWeight: '400' as const,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    fontWeight: '400' as const,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
};

const primaryColors = {
  primary: '#6366f1',     
  onPrimary: '#ffffff',
  primaryContainer: '#e0e7ff',  
  onPrimaryContainer: '#312e81', 
  secondary: '#8b5cf6',   
  onSecondary: '#ffffff',
  secondaryContainer: '#ede9fe', 
  onSecondaryContainer: '#4c1d95', 
  tertiary: '#10b981',     
  onTertiary: '#ffffff',
  tertiaryContainer: '#d1fae5', 
  onTertiaryContainer: '#064e3b', 
  error: '#ef4444',        
  onError: '#ffffff',
  errorContainer: '#fee2e2', 
  onErrorContainer: '#991b1b', 
  surface: '#ffffff',
  onSurface: '#111827',     
  surfaceVariant: '#f9fafb', 
  onSurfaceVariant: '#6b7280', 
  outline: '#d1d5db',       
  outlineVariant: '#e5e7eb', 
  background: '#f9fafb',    
  onBackground: '#111827',   
  surfaceDim: '#f3f4f6',    
  surfaceBright: '#ffffff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f9fafb',
  surfaceContainer: '#f3f4f6',
  surfaceContainerHigh: '#e5e7eb',
  surfaceContainerHighest: '#d1d5db',
  inverseSurface: '#111827',
  inverseOnSurface: '#f9fafb',
  inversePrimary: '#818cf8', 
  shadow: '#000000',
  scrim: '#000000',
  surfaceDisabled: 'rgba(111, 127, 140, 0.12)', 
  onSurfaceDisabled: 'rgba(111, 127, 140, 0.38)',
  backdrop: 'rgba(17, 24, 39, 0.4)', 
  elevation: {
    level0: 'transparent',
    level1: '#ffffff',
    level2: '#ffffff',
    level3: '#ffffff',
    level4: '#ffffff',
    level5: '#ffffff',
  },
};

const darkColors = {
  primary: '#818cf8',      
  onPrimary: '#1e1b4b',
  primaryContainer: '#4338ca', 
  onPrimaryContainer: '#e0e7ff',
  secondary: '#a78bfa',     
  onSecondary: '#ffffff',
  secondaryContainer: '#6d28d9', 
  onSecondaryContainer: '#ede9fe',
  tertiary: '#34d399',     
  onTertiary: '#ffffff',
  tertiaryContainer: '#059669', 
  onTertiaryContainer: '#d1fae5',
  error: '#f87171',        
  onError: '#ffffff',
  errorContainer: '#dc2626', 
  onErrorContainer: '#fee2e2',
  surface: '#1f2937',     
  onSurface: '#f9fafb',    
  surfaceVariant: '#111827', 
  onSurfaceVariant: '#d1d5db', 
  outline: '#4b5563',      
  outlineVariant: '#374151', 
  background: '#111827',    
  onBackground: '#f9fafb',  
  surfaceDim: '#111827',
  surfaceBright: '#374151', 
  surfaceContainerLowest: '#030712', 
  surfaceContainerLow: '#111827',
  surfaceContainer: '#1f2937', 
  surfaceContainerHigh: '#374151',
  surfaceContainerHighest: '#4b5563',
  inverseSurface: '#f9fafb',
  inverseOnSurface: '#111827',
  inversePrimary: '#4f46e5',
  shadow: '#000000',
  scrim: '#000000',
  surfaceDisabled: 'rgba(255, 255, 255, 0.12)',
  onSurfaceDisabled: 'rgba(255, 255, 255, 0.38)',
  backdrop: 'rgba(17, 24, 39, 0.5)',
  elevation: {
    level0: 'transparent',
    level1: '#1f2937', 
    level2: '#374151', 
    level3: '#4b5563', 
    level4: '#6b7280', 
    level5: '#9ca3af', 
  },
};

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: primaryColors,
  fonts: configureFonts({ config: fontConfig }),
  roundness: 12, 
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: darkColors,
  fonts: configureFonts({ config: fontConfig }),
  roundness: 12,
};

export const customColors = {
  light: {
    card: 'rgba(255, 255, 255, 0.9)',      
    cardBorder: 'rgba(229, 231, 235, 0.6)', 
    textSecondary: '#6b7280',              
    textTertiary: '#9ca3af',               
    divider: '#e5e7eb',                    
    success: '#10b981',                    
    warning: '#f59e0b',                    
    info: '#06b6d4',                       
    gradient: {
      primaryStart: '#6366f1',
      primaryEnd: '#4f46e5',
    },
  },
  dark: {
    card: 'rgba(31, 41, 55, 0.7)',        
    cardBorder: 'rgba(55, 65, 81, 0.5)',  
    textSecondary: '#9ca3af',              
    textTertiary: '#6b7280',               
    divider: '#374151',                    
    success: '#34d399',                    
    warning: '#fbbf24',                    
    info: '#22d3ee',                       
    gradient: {
      primaryStart: '#818cf8',
      primaryEnd: '#6366f1',
    },
  },
};

